apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hedgehog.gq
spec:
  secretName: cert-secret
  dnsNames:
  - hedgehog.gq
  - cart.hedgehog.gq
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
