apiVersion: v1
name: robot-shop
version: 1.1.0
home: https://github.com/instana/robot-shop
description: Sample micoservices application
dependencies:
- name: common
  repository: https://akmaanai.github.io/helm/
  tags:
  - spruce-common
  version: 1.x.x
