
## Watch these resources for new DNS records
sources:
  - service
  - ingress

domainFilters:
  - hedgehog.gq
## use google as the dns provider
provider: google
google:
  serviceAccountSecret: external-dns

# These help tell which records are owned by external-dns.
registry: "txt"
txtOwnerId: "external-dns"

## Limit external-dns resources
resources:
  limits:
    memory: 50Mi
  requests:
    memory: 50Mi
    cpu: 10m

## ensure RBAC is enabled
rbac:
  create: true
  apiVersion: v1
policy: upsert-only