targetSystem: "linux"
site: "datadoghq.com"
datadog:
  apiKey: 556f6dde69e3858cb965eaf460a4d8ee
  clusterChecks:
    enabled: true
  clusterAgent:
    enabled: true
  apm:
    portEnabled: true
  dogstatsd:
    port: 8125
    useHostPort: true
    nonLocalTraffic: true
  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
      # ON PORT 8126
